version: "3.8"

services:
  go:
    image: xflawless/goapp:latest
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      - "./go:/app"

  nextjs:
    image: xflawless/nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - "./nextjs:/app"

  wordpress:
    image: xflawless/wordpress:latest
    ports:
      - "80:80"
    environment:
      - WORDPRESS_ENV=production
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${{ secrets.WORDPRESS_DB_USER }}
      - WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}
      - WORDPRESS_DB_NAME=${{ secrets.WORDPRESS_DB_NAME }}
    volumes:
      - "./wordpress:/var/www/html"
      - "./wordpress-uploads:/var/www/html/wp-content/uploads"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    volumes:
      - "./db-data:/var/lib/mysql"

networks:
  default:
    name: myapp-network