name: Go CI

on:
  push:
    paths:
      - 'go/**'
    branches:
      - main
      - '**'

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Cache GolangCI-Lint
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod/github.com/golangci/golangci-lint
        key: ${{ runner.os }}-golangci-lint-${{ hashFiles('go.sum') }}
    - name: Install Go linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
    - name: Run Go tests
      run: go test ./...
      working-directory: go
    - name: Lint Go code
      run: golangci-lint run ./...
      working-directory: go
    - name: Build and Push Docker Image
      if: success()
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t xflawless/goapp:latest .
        docker push xflawless/goapp:latest
      working-directory: go