name: WordPress CI

on:
  push:
    paths:
      - 'wordpress/**'
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: WordPress Coding Standards check
        uses: 10up/wpcs-action@stable
        with:
          enable_warnings: false 
          paths: '.' 
          excludes: '' 
          standard: 'WordPress' 
          standard_repo: '' 
          repo_branch: 'main'
          phpcs_bin_path: 'phpcs' 
          use_local_config: 'true'
      - name: Build and Push Docker Image
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t xflawless/wordpress:latest .
          docker push xflawless/wordpress:latest
        working-directory: wordpress